INSERT INTO `acao` (`id`,`nome`) VALUES
 (1, 'PERM_ADMIN'),
 (2, 'PERM_LISTAR_EMPRESTIMO'),
 (3, 'PERM_DEVOLVER_LIVRO'),
 (4, 'PERM_ADD_LIVRO'),
 (5, 'PERM_ALUGAR_LIVRO'),
 (6, 'PERM_ATUALIZAR_LIVRO'),
 (7, 'PERM_REMOVER_LIVRO'),
 (8, 'PERM_DEVOLVER_LIVRO'),
 (9, 'PERM_ADD_USUARIO'),
 (10, 'PERM_ATUALIZAR_USUARIO'),
 (11, 'PERM_DELETAR_USUARIO');